default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 

development:
  <<: *default
  database: hamigaki_development
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: hamigaki_test

production:
  <<: *default
  adapter: postgresql
  database: hamigaki_development
  url: <%= ENV['DATABASE_URL'] %>