default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hamigaki_development

test:
  <<: *default
  database: hamigaki_test

production:
  primary: &primary_production
    <<: *default
    database: hamigaki_production
    username: hamigaki
    password: <%= ENV["HAMIGAKI_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hamigaki_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hamigaki_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hamigaki_production_cable
    migrations_paths: db/cable_migrate